### ISSUE TITLE
TOKEN INVALID

### ISSUE THREAD

**Issue by JimmyH6** [AkshatOP/Poketwo-Autocatcher#11]
Geting token Invalid error when running node.js

**Comment by JimmyH6** [comment]
![Bildschirmfoto 2024-01-10 um 13 37 35](https://github.com/AkshatOP/Poketwo-Autocatcher/assets/156187746/0ffd0421-9cc3-4622-a9d6-0839409e4eb8)

**Comment by AkshatOP** [comment]
Re-check the token either it's actually invalid or not written correctly in config files
