### ISSUE TITLE
Wrong names

### ISSUE THREAD

**Issue by jonraminoski** [AkshatOP/Poketwo-Autocatcher#5]
Everytime i try to add a name thats wrong it messes up and i have to delete the name to be able to use the replit again

**Comment by AkshatOP** [comment]
Send me an example of how you edit it? 
For example take

Wrong name as pokuchu 
And correct name as pikachu

Cuz I clearly mentioned how to edit the json

**Comment by jonraminoski** [comment]
[![image](https://github.com/AkshatOP/Poketwo-Autocatcher/assets/54284716/0a1a2f40-a323-4dd4-81e2-102d977277c7)]()

**Comment by jonraminoski** [comment]
Exactly how the others are done 
Lombre is coming up 'ombre 
Flabebe has a dot on the end

**Comment by jonraminoski** [comment]
![image](https://github.com/AkshatOP/Poketwo-Autocatcher/assets/54284716/bf2ca62b-153a-4abd-ad5a-e6e86acc64c2)
This is the error i get

**Comment by AkshatOP** [comment]
I can't guess it without knowing what is written in position 5375
Copy paste the namefix.json in pastebin or somewhere and send it over I will have a look and will respond where to rectify

**Comment by jonraminoski** [comment]
https://replit.com/@jonraminoski/Poketwo-Autocatcher?mobileWebview=1&mobileBridge=1&hideBottomBar=1&forceTheme=replitLight&fun=1#namefix.json

**Comment by AkshatOP** [comment]
Fixed the issue through discord DMs
