### ISSUE TITLE
Its Not Starting in Replit 

### ISSUE THREAD

**Issue by Yuv120** [AkshatOP/Poketwo-Autocatcher#7]
![Screenshot_20230903-112240](https://github.com/AkshatOP/Poketwo-Autocatcher/assets/130856623/1a941990-b80a-4890-b1b8-27f625bcefc5)

Error pls solve it

**Comment by DaHomieMiggy** [comment]
are you mobile or pc?

**Comment by Yuv120** [comment]
> 

Mobile

**Comment by DaHomieMiggy** [comment]
dm me dahomiemiggy

**Comment by AkshatOP** [comment]
thanks for the miggy :D
